#!/usr/bin/python
# -*- coding: utf-8 -*-

jobs = [
    '',
    '23andMe',
    '2sigma',
    '500px',
    '6sense',
    'A thinking ape',
    'A9',
    'ANDigital',
    'Academia',
    'Achievers',
    'Acorns',
    'Acquia',
    'Activision',
    'Addepar',
    'Adobe',
    'Affirm',
    'Ahrefs',
    'Airbnb',
    'Airtable',
    'Akuna',
    'Akuna capital',
    'Algebraix',
    'Algolia',
    'AllianceBernstein',
    'AltSchool',
    'Amazon',
    'Amd',
    'American Express',
    'American express',
    'Amino',
    'Amobee',
    'Ancestry',
    'Angellist',
    'AppFolio',
    'AppNexus',
    'Appdynamics',
    'Appian',
    'Apple',
    'Applied Intuition',
    'Applied intuition',
    'Apptio',
    'Aptible',
    'Aquent',
    'Arista',
    'Asana',
    'Aspiration Software',
    'At&t',
    'Atlassian',
    'Atomic',
    'Audible',
    'August',
    'Aurora',
    'Auth0',
    'Authentise',
    'Autodesk',
    'AutomatedInsights',
    'Automattic',
    'Awesense',
    'BambooHR',
    'Belvedere Trading',
    'Benchling',
    'Benchsci',
    'Bending Spoons',
    'Bessemer Fellowship',
    'Betterment',
    'Bill.com',
    'BitTiger',
    'BitTorrent',
    'Bitly',
    'Bitnami',
    'Blackboard',
    'Blackrock',
    'Blackstone',
    'Blend',
    'Blend Labs',
    'Blend labs',
    'Blizzard',
    'Bloomberg',
    'Bloomz',
    'Blue Origin',
    'Blue apron',
    'Bolt',
    'Bonuz',
    'BookBub',
    'Booking.com',
    'Box',
    'Braintree',
    'Braze',
    'Breakthrough',
    'Brigade',
    'BuildASign',
    'BuildZoom',
    'Bumble',
    'Bungie',
    'Busbud',
    'BuzzFeed',
    'ByteDance',
    'C3.ai',
    'CBRE Build',
    'CME Group',
    'CTRL-Lab',
    'Cadre',
    'Cambly',
    'Canada gov?',
    'Canary',
    'Capital One',
    'Capital one',
    'Capsule',
    'Captain401',
    'Carbon',
    'Carecru',
    'Carousell',
    'Casetext',
    'Casper',
    'Catchpoint',
    'Cengage',
    'Centro',
    'Chan Zuckerberg Initiative',
    'Chaordic',
    'Checkout all the jobs on Angellist',
    'Checkr',
    'Cheesecake Labs',
    'Chewy',
    'Chexology',
    'Ciena',
    'CircleUp',
    'Cisco',
    'Citadel',
    'Citrix',
    'Classy',
    'ClearSlide',
    'Clever',
    'Clippings',
    'Cloudera',
    'Clue',
    'Clustrix',
    'Clutter',
    'Cockroach labs',
    'Codecademy',
    'Codefights',
    'Codeship',
    'Cogo Labs',
    'Coinbase',
    'Collective Health',
    'Collins Aerospace',
    'Color',
    'Compass',
    'Confluent',
    'Convoy',
    'Cora',
    'CoreOS',
    'CornerStone OnDemand',
    'Couchbase',
    'Couchsurfing',
    'Counsyl',
    'Coursera',
    'CreditKarma',
    'CrowdRise',
    'CrowdStar',
    'Crowdstrike',
    'Cruise',
    'CrunchBase',
    'Csa',
    'Cumulus Networks',
    'Curalate',
    'Curse',
    'Curtsy',
    'Cvent',
    'D.E. Shaw',
    'DJI',
    'DOT Digital Group',
    'Databricks',
    'Datadog',
    'Dell',
    'Delphix',
    'Demandware',
    'Demonware',
    'Dialpad',
    'DigitalOcean',
    'Discover',
    'Disqus',
    'Docker',
    'DocuSign',
    'Docusign',
    'DollarShaveClub',
    'DoorDash',
    'Doordash',
    'Dot & Bo',
    'DraftKings',
    'DroneDeploy',
    'Dropbox',
    'Duolingo',
    'ETH Zuerich',
    'Ea',
    'EagleView',
    'Eagleview',
    'Earny',
    'Ebay',
    'Ecobee',
    'EdX',
    'Edmodo',
    'Edmunds',
    'Elastic path software',
    'Elasticsearch',
    'Electronic Arts',
    'Element.ai',
    'Elementai',
    'Elemental Technologies',
    'EnergySavvy',
    'Enfusion',
    'Entelo',
    'Epic',
    'Esri',
    'Essential designs',
    'Etsy',
    'Eventbrite',
    'Evernote',
    'Exan',
    'Expedia',
    'Facebook',
    'Factual',
    'Fanatics Inc.',
    'Faraday Future',
    'Farfetch',
    'Fast Enterprises',
    'Fast enterprises',
    'Fastly',
    'Fictiv',
    'Fidelity Investments',
    'Fieldbook',
    'Figma',
    'Fitbit',
    'Five Rings Capital',
    'FiveStars',
    'Fivestars',
    'Flatiron',
    'Flexport',
    'Flipboard',
    'Flipkart',
    'Flipp',
    'Forex Factory',
    'Fortinet',
    'Foursquare',
    'Front',
    'Frozen Mountain',
    'Fujitsu ai',
    'Funding Circle',
    'Garmin',
    'General Assembly',
    'General fusion',
    'General motors',
    'GetYourGuide',
    'Gigster',
    'GitHub',
    'GitLab',
    'Github',
    'Gitlab',
    'Glitch (fogcreek)',
    'Global relay',
    'GoDaddy',
    'Godaddy',
    'Goldman Sachs',
    "Goldman sach's",
    'Google',
    'GrammaTech',
    'Grammarly',
    'Grand Rounds',
    'Grand rounds',
    'Gree',
    'Greenhouse',
    'Groceristar',
    'Groupon',
    'GrubHub',
    'Guidewire',
    'GumGum',
    'Gusto',
    'HP Enterprise',
    'Hacker Fellows',
    'HackerRank',
    'Haiku Deck',
    'Hailo',
    'Handshake',
    'Hart, Inc.',
    'Helix',
    'Helpling',
    'Hewlett packard enterprise',
    'Hipmunk',
    'HomeAway',
    'Honey',
    'Hootsuite',
    'Houston Mechatronics',
    'Hp',
    'HubSpot',
    'Hubspot',
    'Hudson River Trading',
    'Hudson river trading',
    'Hulu',
    'Humble bundle',
    'Huobi',
    'Hyland',
    'IBM',
    'IFTTT',
    'IMC Trading',
    'IXL Learning',
    'Ibm',
    'Idealab',
    'Idemia',
    'IgnitionOne',
    'Illumio',
    'Imgur',
    'Improbable',
    'InMobi',
    'Indeed',
    'Indiegogo',
    'Infinera',
    'InfluxDB',
    'InstaCart',
    'Instacart',
    'Instructure',
    'Integral Ad Science',
    'Intellisis',
    'Intentional',
    'InterSystems',
    'Interactive Intelligence',
    'Intercom',
    'Intrepid Pursuits',
    'Intuit',
    'Invoice2go',
    'Ironclad',
    'JP Morgan Chase',
    'Jane Street',
    'Jane street',
    'Jawbone',
    'Jet',
    'Jet propulsion lab',
    'JetBrains',
    'Jiminny',
    'Jive',
    'Jobvite',
    'Joyent',
    'Jp morgan technology analyst',
    'Jpmorgan chase',
    'Jump Trading',
    'JustWatch',
    'Karat',
    'Kayak',
    'KeepSafe',
    'KeepTruckin',
    'Kensho',
    'Khan Academy',
    'Khan academy',
    'Kickstarter',
    'Kik',
    'Kinnek',
    'Kite.com',
    'Kiva',
    'Klarna',
    'Kleiner Perkins Fellows Program',
    'Knowles',
    'Knowt',
    'Konami',
    'Kronos',
    'Laserfiche',
    'Latch',
    'Lattice engines',
    'Launchable',
    'Leetcode',
    'Leidos',
    'LendUp',
    'Lever',
    'Liberty mutual insurance',
    'Lifesize',
    'Liftoff',
    'Lime',
    'Limeade',
    'LinkedIn',
    'Linkedin',
    'Linode',
    'Lithium',
    'LiveRamp',
    'Liveramp',
    'Livescribe',
    'Lob',
    'Loblaw',
    'Localline',
    'Lockheed Martin',
    'Logitech',
    'Looker',
    'Lucid',
    'Lucid Software',
    'Lumentum',
    'Luxe',
    'Lyft',
    'Lyft Level 5',
    'Lytx',
    'MLab',
    'Machine Zone',
    'Magic',
    'MailChimp',
    'Mark 43',
    'Marketo',
    'Marvell',
    'Mastercard',
    'Matco Tools',
    'MathWorks',
    'Mathworks',
    'Matician',
    'Mattermark',
    'Matterport',
    'Mcafee',
    'Medallia',
    'Medium',
    'Meetup',
    'MemSQL',
    'Memsql',
    'Meraki',
    'Mesosphere',
    'Meteor',
    'Metromile',
    'Microsoft',
    'Mind Candy',
    'MindTouch',
    'MixBit',
    'Mixmax',
    'Mixpanel',
    'Mobify',
    'Mojio',
    'Mongo',
    'MongoDB',
    'Mongodb',
    "Moody's",
    'Motion metrics',
    'Moz',
    'Mozilla',
    'MuleSoft',
    'Munchery',
    'Narrative Science',
    'Neeva',
    'NerdWallet',
    'Nervana Systems',
    'Nest',
    'Netflix',
    'Neuralink',
    'Neurio',
    'New Relic',
    'Nexmo',
    'Nextdoor',
    'Niantic',
    'Nintendo',
    'Nulab',
    'Nulogy',
    'Nuro',
    'Nutanix',
    'Nvidia',
    'OSIsoft',
    'Oath',
    'Oblong',
    'Okta',
    'Omada health',
    'OneLogin',
    'Onefootball',
    'Open Whisper Systems',
    'OpenTable',
    'OpenX',
    'Openai',
    'Opendoor',
    'Opener',
    'Operator',
    'Optimizely',
    'Oracle',
    'Oscar',
    'Oscar Health',
    'Outreach',
    'PEngine',
    'Pagefreezer',
    'Pagerduty',
    'Palantir',
    'Palo Alto Networks',
    'Pandora',
    'Particle',
    'PayPal',
    'Paycom',
    'Paylocity',
    'Paypal',
    'Paytm Labs',
    'Peak6',
    'Pendo',
    'Percieve',
    'Petal',
    'Picwell',
    'Pinterest',
    'Pivotal',
    'Pixar',
    'Plaid',
    'Platform9',
    'Playstation',
    'PlushCare',
    'Pocket Gems',
    'Podium',
    'Poshmark',
    'Postmates',
    'Prezi',
    'Priceline',
    'Prism',
    'Pristine',
    'Procore',
    'Procore Technologies',
    'Prominic',
    'Propeller',
    'Pure Storage',
    'Pure storage',
    'Qlik',
    'Qualcomm',
    'Qualtrics',
    'Quantcast',
    'Qubole',
    'Quip',
    'Quizlet',
    'Quora',
    'Quorum',
    'RBC',
    'ROBLOX',
    'Rackspace',
    'Radius',
    'Rakuten',
    'ReadMe',
    'Recruit holdings (tokyo)',
    'Red Hat',
    'Red Nova Labs',
    'Red Ventures',
    'Red hat',
    'RedMart',
    'Redbooth',
    'Redbull',
    'Reddit',
    'Redfin',
    'Redis-Labs',
    'Relativity',
    'Remitly',
    'ResearchGate',
    'Respawn',
    'Resultados Digitais',
    'RetailNext',
    'Retailmenot',
    'Rimeto',
    'Riot Games',
    'RiskIQ',
    'Roadtrippers',
    'Robinhood',
    'Roblox',
    'Rockset',
    'Roku',
    'Rover.com',
    'Rubrik',
    'SADA Systems',
    'SAS',
    'SKHMS',
    'SSi Micro',
    'Salesforce',
    'Samsara',
    'Samsung',
    'Sandvine',
    'Sap',
    'ScoreBig',
    'Scribd',
    'Seamless',
    'SeatGeek',
    'Segment',
    'SelfMade',
    'SendGrid',
    'Sensay',
    'Sensus',
    'ServiceNow',
    'Servicenow',
    'Shazam',
    'SheerID',
    'Shopify',
    'ShoreTel',
    'Shutterfly',
    'Sift Science',
    'SigOpt',
    'Signifyd',
    'SimplyCredit',
    'Skillshare',
    'Skip',
    'Skurt',
    'Skybox labs',
    'Slack',
    'Sledgehammer',
    'Slice',
    'Smarking',
    'SmartSheet',
    'SmartThings',
    'Smartsheet',
    'Smule',
    'Snapchat',
    'Snowflake',
    'SocialBase',
    'Socotra',
    'Sony',
    'Sony Interactive Entertainment PlayStation',
    'Sophos',
    'SoundCloud',
    'Source Intelligence',
    'SpaceX',
    'Spacex',
    'Spatial',
    'Splunk',
    'Spotify',
    'Sprout Social',
    'Square',
    'Square space',
    'Squarespace',
    'StackPath',
    'Stantec',
    'Stateless',
    'Stealth startup',
    'SteelHouse',
    'Stevens Capital Management',
    'Stitch Fix',
    'Strava',
    'Stripe',
    'Stubhub',
    'Study.com',
    'SugarCRM',
    'Sumo Logic',
    'Sumo logic',
    'Sunlink',
    'SurveyMonkey',
    'Symphony',
    'T-Mobile',
    'TED',
    'Tableau',
    'Taboola',
    'Taco Bell, Corporate',
    'Takt',
    'Tango',
    'Tantalus systems',
    'Tapad',
    'Taskus',
    'Teachable',
    'Tech.LA Fellowship',
    'Teespring',
    'Telenav',
    'Tesla',
    'TextNow',
    'The Artist Union',
    'The Climate Corporation',
    'The Home Depot',
    'The Internet Archive',
    'The League',
    'The Teamworthy Fellowship',
    'The Washington Post',
    'ThoughtSpot',
    'ThoughtWorks',
    'Thumbtack',
    'TiVo',
    'Tile',
    'Tillster',
    'Tinder',
    'Tint',
    'Toast',
    'Top Hat',
    'Top hat',
    'Trail',
    'Transfix',
    'Travis CI',
    'Treyarch',
    'TripActions',
    'TripAdvisor',
    'Tripactions',
    'Trustpilot',
    'Trustwave',
    'Tubemogul',
    'Tubular labs',
    'Tumblr',
    'Twilio',
    'Twine Labs',
    'Twitch',
    'Twitter',
    'Two Roads',
    'Two Sigma',
    'Uber',
    'Udacity',
    'Uipath',
    'Unilogik',
    'Unity',
    'Uplight',
    'Upwork',
    'Urban Massage',
    'VEVO',
    'VHX',
    'Vail',
    'Valkyrie',
    'Valve',
    'Veeva',
    'Venmo',
    'Vertafore',
    'Viasat',
    'Viget',
    'Vimeo',
    'Virtu Financial',
    'Virtu financial',
    'Visa',
    'Vision critical',
    'Vmware',
    'Vox Media',
    'Vultr',
    'Wattpad',
    'WayUp',
    'WeRide.ai',
    'Wealthfront',
    'Wealthsimple',
    'Weebly',
    'Whitepages',
    'Wikimedia Foundation',
    'Williams-Sonoma, Inc',
    'WillowTree',
    'Willowtree',
    'Wish',
    'Wolt',
    'Wolverine Trading',
    'Work Market',
    'Workiva',
    'World wide technology',
    'Xero',
    'Yelp',
    'Yext',
    'YouNow',
    'Zalando',
    'Zappos',
    'ZenMate',
    'Zendesk',
    'Zenefits',
    'Zillow',
    'ZocDoc',
    'Zoom',
    'Zoosk',
    'Zscaler',
    'Zuora',
    'Zynga',
    '[The Vanguard Group',
    'ark43',
    'change.org',
    'datto',
    'eHarmony',
    'esla',
    'esri',
    'frame.ai',
    'hone2Action',
    'iCIMS',
    'oblox',
    'os Alamos National Lab',
    'ozilla',
    'rubrik',
    'uSimple',
    'w York Times',
    'xs',
    ]

applied_jobs = set()


def pop_add():
    job = jobs.pop()
    print job
    applied_jobs.add(job)



			